version: '1.0'
# docker compose -f docker-compose.dev.yml up -d --build
# docker compose -f docker-compose.dev.yml down -v

# -d : 서비스 백그라운드로 실행
# --force-recreate : 컨테이너를 지우고 새로 생성
# --build : 서비스 시작 전 이미지를 새로 생성
# -f 기본으로 제공하는 docker-compose.yml이 아닌 다른 파일명을 실행할 때 사용

services:
  front:
    image: youth2030-myhome-front
    container_name: youth2030-myhome-front
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app
      - front:/app/node_modules
    
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
      # target: unit-test
    image: youth2030-myhome-back
    container_name: youth2030-myhome-back
    restart: always
    volumes:
      - ./back:/app
      - back:/app/node_modules
      # - .git:/app/.git

  nginx:
    image: nginx
    container_name: youth2030-myhome-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - front
      - back

volumes:
  front:
  back:
