version: '1.0'
# docker compose -f docker-compose.yml up -d
# docker compose -f docker-compose.yml down -v

services:
  #  nginx:
  #    image: nginx:latest
  #    container_name: youth2030-myhome-nginx
  #    restart: always
  #    ports:
  #      - 10000:80
  #    volumes:
  #      - ./nginx:/etc/nginx/conf.d
  #    depends_on:
  #    #        - front

  database:
    image: mysql:latest
    container_name: youth2030-myhome-database
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - ${DATABASE_DIR}:/var/lib/mysql

volumes:
  front:
  back:
  worker:


