FROM node:lts-alpine as dev

WORKDIR /app/back

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

EXPOSE 3000

CMD [ "yarn", "start:dev" ]

#############################################################

FROM dev as unit-test

ENV GIT_WORK_TREE=/app/back GIT_DIR=/app/.git

RUN apk update && \
    apk add git

CMD [ "yarn", "test:watch" ]
