# FROM node:lts-alpine as dev
FROM node:lts-alpine

WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn install && yarn cache clean

# COPY . .

EXPOSE 3000

CMD [ "yarn", "start" ]

#############################################################

# FROM dev as unit-test

# ENV GIT_WORK_TREE=/app/back GIT_DIR=/app/.git

# RUN apk update && \
#     apk add git

# CMD [ "yarn", "test:watch" ]
